# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:  "{Onto,Techno,Musico}logies"
subtitle: "Musical notes from the [http://oerc.ox.ac.uk](University of Oxford e-Research Centre)"
email: david.weigl@oerc.ox.ac.uk
description: > # this means to ignore newlines until "baseurl:"
    Technical blog on Music and Digital Musicology at the Oxford e-Research Centre
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oerc-music.github.io" # the base hostname & protocol for your site, e.g. http://example.com twitter_username: musicog 
twitter_username: OxfordeResearch 
github_username:  oerc-music

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
